@RestaurantsAPI_HostAddress = https://localhost:7083

GET {{RestaurantsAPI_HostAddress}}/api/restaurants

###


GET {{RestaurantsAPI_HostAddress}}/api/restaurants/2

###


POST {{RestaurantsAPI_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Tasty Bites",
  "Description": "A cozy restaurant serving a variation of food",
  "Category": "Indian",
  "ContactEmail": "tesd@c.com",
  "ContactNumber": "5555-555555",
  "PostalCode": "33-222"
}
###

DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/3

###


PATCH {{RestaurantsAPI_HostAddress}}/api/restaurants/522
Content-Type: application/json

{
  "Name": "Sample patch",
  "Description": "adawddawddawdaw",
  "HasDelivery" : true
}

###

POST {{RestaurantsAPI_HostAddress}}/api/restaurants/2/dishes
Content-Type: application/json

{
  "Name": "Spags",
  "Description": " awdwadwddstyle",
  "Price" : 44,
  "KiloCalories": 1
}

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/111/dishes/11

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/221/dishes

###

DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/2/dishes

###
