@RestaurantsAPI_HostAddress = https://localhost:7083

GET {{RestaurantsAPI_HostAddress}}/api/restaurants

###


GET {{RestaurantsAPI_HostAddress}}/api/restaurants/5

###


POST {{RestaurantsAPI_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Tasty Bites",
  "Description": "A cozy restaurant serving a variation of food",
  "Category": "Indian",
  "ContactEmail": "tesd@c.com",
  "ContactNumber": "5555-555555",
  "PostalCode": "33-222"
}
###